apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: product-service-deployment
spec:
   replicas: 2
   revisionHistoryLimit: 100
   template:
      metadata:
         labels:
            app: product-service
      spec:
         containers:
         - name: product-service-app
           image: gcr.io/practice-239003/product-service
           ports:
           - containerPort: 8080